ci: speed up js sdk release job (#3213)

diff --git a/api/client/javascript/Makefile b/api/client/javascript/Makefile
--- a/api/client/javascript/Makefile
+++ b/api/client/javascript/Makefile
@@ -8,6 +8,27 @@ generate: ## Generate JavaScript SDK
 	pnpm build
 	pnpm test
 
+# Warning: keep in sync with .dagger/release.go for now
+.PHONY: publish-javascript-sdk
+publish-javascript-sdk: ## Publish JavaScript SDK
+	$(call print-target)
+	@if [ -z "$$JS_SDK_RELEASE_VERSION" ]; then \
+		echo "ERROR: JS_SDK_RELEASE_VERSION is required"; \
+		echo "Usage: JS_SDK_RELEASE_VERSION=1.2.3 make publish-javascript-sdk [JS_SDK_RELEASE_TAG=beta]"; \
+		exit 1; \
+	fi
+
+	@if [ -z "$$JS_SDK_RELEASE_TAG" ]; then \
+		echo "ERROR: JS_SDK_RELEASE_TAG is required"; \
+		echo "Usage: JS_SDK_RELEASE_VERSION=1.2.3 make publish-javascript-sdk [JS_SDK_RELEASE_TAG=beta]"; \
+		exit 1; \
+	fi
+
+	pnpm --frozen-lockfile install
+	pnpm version "$${JS_SDK_RELEASE_VERSION}" --no-git-tag-version
+	CACHE_BUSTER="$$(date --rfc-3339=seconds)" pnpm publish --no-git-checks --tag "$${JS_SDK_RELEASE_TAG}"
+	@echo "✅ Published $${JS_SDK_RELEASE_TAG} JavaScript SDK version $${JS_SDK_RELEASE_VERSION} with tag $${JS_SDK_RELEASE_TAG}"
+
 .PHONY: help
 .DEFAULT_GOAL := help
 help:
